cartshop/urls.py
from django.urls import path
from . import  views

app_name= 'cartshop' 


urlpatterns = [

     path('', views.cart, name='cart'),
     
   
]

ecommerxal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from users import urls




urlpatterns = [

    path('', include('users.urls')),
    path('productos/', include('products.urls')),
    path('carrito/', include('cartshop.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import ProductDetailView, ProductListView, ProductSearchListView

app_name= 'products' 


urlpatterns = [

     path('', ProductListView.as_view(), name='users_list'),
     path('search', ProductSearchListView.as_view(), name='search'),
     path('<slug:slug>', ProductDetailView.as_view(), name='Detail_product'),
   
]

users/urls.py
from django.contrib import admin
from django.urls import path

from . import views
from products.views import ProductListView

urlpatterns = [

    path('users/', views.user_add, name='users_add'),
    path('users/login', views.login_user, name='login'),
    path('users/logout', views.logout_user, name='logout'),
    path('users/register', views.register_user, name='register'),
]

cartshop/models.py
import uuid
from django.db import models
from clients.models import User
from products.models import Product
from django.db.models.signals import pre_save


# Create your models here.
class CartShop(models.Model):
    cart_id= models.CharField(max_length=100, null=False, blank=False, unique=True)
    user= models.ForeignKey(User, null=True, blank= True, on_delete="models.CASCADE")
    product = models.ManyToManyField(Product)
    subtotal = models.DecimalField(default=0.0, max_digits=8, decimal_places=2)
    total = models.DecimalField(default=0.0, max_digits=8, decimal_places=2) 
    create_at= models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.cart_id

def set_cart_id(sender, instance, *args, **kwargs):
    if not instance.cart_id:
        instance.cart_id= str(uuid.uuid4())

pre_save.connect(set_cart_id, sender=CartShop)

categories/models.py
from django.db import models
from products.models import Product


# Create your models here.
class Category (models.Model):
    title= models.CharField(max_length=50)
    description=models.TextField()
    products = models.ManyToManyField(Product, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

clients/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    def get_full__name(self):
        return '{} {}'.format(self.first_name, self.last_name)

class customer(User):
    class Meta:
        proxy = True
    def get_products(self):
        return []

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio= models.TextField()

products/models.py
from django.db import models
from django.utils.text import slugify
from django.db.models.signals import pre_save
from django.utils import timezone
import uuid
# Create your models here
class Product(models.Model):
    title= models.CharField(max_length=50)
    description= models.TextField()
    image = models.ImageField(upload_to="products/", null=False, blank=False)
    slug = models.SlugField(null=False, blank=False, unique=True)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0.0)
    create_at= models.DateTimeField(auto_now=True)

    #def save(self, *args, **kwargs):
     #   self.slug= slugify(self.title)
      #  super(Product,self).save(*args, **kwargs)

    def __str__(self):
        return self.title
def set_slug(sender,instance, *args, **kwargs):
    if instance.title and not instance.slug:
        slug = slugify(instance.title)
    
        while Product.objects.filter(slug=slug).exists():
            slug = slugify(
               '{}-{}'.format(instance.title, str(uuid.uuid4())[:2]
               )
            )
        instance.slug = slug

pre_save.connect(set_slug, sender=Product)

cartshop/views.py
from django.shortcuts import render
from .models import CartShop
from .utils import get_or_create_cart
# Create your views here.
def cart(request):
    

    cart = get_or_create_cart(request)

    return render(request, 'cartshop/cart.html',{
        
    })

clients/views.py
from django.shortcuts import render

# Create your views here.

products/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .models import Product
from django.db.models import Q
# Create your views here.
class ProductListView(ListView):
    template_name= 'users/users_index.html'
    queryset = Product.objects.all().order_by('-id')

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context['message']='Listado de productos'
        return context

class ProductDetailView(DetailView):
    model=Product
    template_name='products/product.html'

    def get_context_data(self, **kwargs):

      context = super().get_context_data(**kwargs)
  
      return context

class ProductSearchListView(ListView):
    template_name= 'products/search.html'
  

    def get_queryset(self):
        filters= Q(title__icontains= self.query()) | Q(category__title__icontains= self.query())
        return Product.objects.filter(filters)
    
    def query(self):
        return self.request.GET.get('q')
    
    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context['query']= self.query()
        context['count']= context['product_list'].count()
        return context

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from .form import RegisterForm
from products.models import Product
from clients.models import User

# Create your views here.


def user_add(request):
 
    return render(request, 'index.html')


def login_user(request):
    if request.user.is_authenticated:
         return redirect('users_add')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        print(user)
        if user:
            login(request, user)
            messages.success(request, 'Bienvenido {}'.format(user.username))
            return redirect('users_add')

        else:
            messages.error(request, 'Usuario o contraseña no valido')

    return render(request, 'users/login.html')


def logout_user(request):
    logout(request)
    messages.success(request, 'Sesión finalizada')
    return redirect('login')


def register_user(request):
    if request.user.is_authenticated:
         return redirect('users_add')

    form = RegisterForm(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        new_user = form.save()

        if new_user:
            login(request, new_user)
            messages.success(request, 'Usuario creado exitosamente')
            return redirect('users_add')

    return render(request, 'users/register.html', {'form': form

                                                   })

cartshop/templates/cartshop/cart.html
{% extends "users/base.html" %}
{% block content %}

<H2>CARRITO DE COMPRA</H2>

{% endblock content %}

<H2>CARRITO DE COMPRA</H2>

ecommerxal/templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <script
        src="https://code.jquery.com/jquery-3.4.1.slim.js"
        integrity="sha256-BTlTdQO9/fascB1drekrDVkaKd9PkwBymMlHOiG+qLI="
        crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>ecommerce Xalapa</title>
</head>
<body>
      <div class="cointainer">
        <div class="row">
            {% block content %}
            {% endblock content %}
        </div>
      </div>
</body>
        <script src="{% static 'js/main.js' %}"></script>
</html>

ecommerxal/templates/index.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>ecommerce Xalapa</title>
</head>
<body>
    <h1>hola mundo</h1>
</body>
        <script src="{% static 'js/main.js' %}"></script>
</html>

ecommerxal/templates/users/users_index.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>ecommerce Xalapa</title>
</head>
<body>
    <h1>hola mundo</h1>
</body>
        <script src="{% static 'js/main.js' %}"></script>
</html>

products/templates/products/product.html
{% extends "users/base.html" %}
{% block content %}
    <div class="col-3">
        {%if product.image%}
        <img src="{{product.image.url}}" alt="imagen-product" width="200" height="200">
        {%endif%}
    </div>
    <div class="col">
    <div  class="h1">
        {{product.title}}
    <div class="h5 font-weight-bold">
        Precio: <span class="text-danger">$ {{product.price}}</span>
    </div>
    <div class="h3">
       <p> {{product.description}}</p>
    </div>
    </div>

   
{% endblock content %}

products/templates/products/search.html
{% extends "users/base.html" %}
{% block content %}
    
    <div class ="col">
        {%include "products/snippets/search.html" %}
         <hr>
         <p>Resultados para: {{query}} ({{count}})
        {%include "products/snippets/list.html" %}
   </div>
{% endblock content %}

products/templates/products/snippets/list.html
        

            <div class="row">
                
                {%for product in object_list%} 
                    <div class="col-3 mt-5">
                         
                        {%include "products/snippets/product.html" with field=product %}
                        
                    
                    </div>
                
                {%endfor%}
            
            </div>
  

products/templates/products/snippets/product.html
<div class="card h-100">
    {%if field.image%}
        <img src="{{field.image.url}}" alt="Imagen del producto" height=300>
    {%endif%}  
    <div class="card-body">
        <h5 class="card-title">{{field.title}}</h5>
        <p class="card-text">{{field.description}}</p>
        <a href="{% url 'products:Detail_product' field.slug %}" class="btn btn-primary">ver más</a> 
    </div>
</div>

products/templates/products/snippets/search.html
    <form action="{%url 'products:search'%}">
    <div class="input-group">
        <input type="text" name="q" value="{{query}}" class="form-control" placeholder="Buscar">
        <div class="input-group-append">
            <input type="submit" name=""  value="Buscar" class="btn btn-primary">
        </div>
        
    </div> 
</form>

users/templates/index.html
{% extends "users/base.html" %}
{%load static%}

 {%block content%}
    <div class="col">
    <h1>Hola </h1>
    </div>
 {%endblock content%}

users/templates/users/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <script
        src="https://code.jquery.com/jquery-3.4.1.slim.js"
        integrity="sha256-BTlTdQO9/fascB1drekrDVkaKd9PkwBymMlHOiG+qLI="
        crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        <script src="https://kit.fontawesome.com/62a4864460.js" crossorigin="anonymous"></script>
        <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>ecommerce Xalapa</title>
</head>
<body>
      {% include "users/navbar.html" %}
      <div class="container">
        {% include "users/message.html" %}
        <div class="row mt-3">
            {% block content %}
            {% endblock content %}
        </div>
      </div>
</body>
        <script src="{% static 'js/main.js' %}"></script>
</html>

users/templates/users/login.html
{% extends "users/base.html" %}
{%load static%}
{% block content %}
    <div class="container">
            
                <div class="col">
                    <h2>Login</h2>
                <!--Formulario-->
                    <Form method="post">
                            {% csrf_token %}
                        <div class="form-group">
                            <label for="username">Username</label>
                            <input type="text" name ='username' class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="password">Password</label>
                            <input type="password" name='password' class="form-control">
                        </div>
                        <button type="submit" class="btn btn-primary">Login</button>
                    </Form>
                </div>
    </div>
{% endblock content %}

users/templates/users/message.html
{%if messages%}
    {%for message in messages  %}
                
                <div class="alert {% if message.tags == 'success'%} alert-success {%else%} alert-danger{%endif%}">
                    <button type="button" class="close" data-dismiss="alert">X</button>
                    {{message}}
                </div>
    {%endfor%}
{%endif%}

users/templates/users/navbar.html
{% url 'login' as login%}
{% url 'register' as register%}
{% url 'cartshop:cart' as cart%}

<nav class="navbar navbar-expand-md bg-dark navbar-dark ">
    <a href="{% url 'products:users_list'%}" class="navbar-brand">ecommerxal</a>

    

    <button type="button" class="navbar-toggler navbar-toggler-right" data-target="#navb" data-toggle="collapse">
        <span class="navbar-toggler-icon"></span>
    </button>
    
    <div id="navb" class="navbar-collapse collapse hide">
        <ul class="navbar-nav">
            <li class="nav-item {%if request.path == cart%}active{%endif%}" >
            <a class="nav-link" href="{{cart}}">Mi carrito <span class ="fas fa-shopping-cart"></a>
            </li>
        </ul>

        <ul class="nav navbar-nav ml-auto ">
                {%if user.is_authenticated%}
                    <li class="navbar-item">
                            <a href ="{%url 'logout'%}" class="nav-link">
                            <span class="fas fa-sign-in-alt"></span>   
                            Logout</a>
                    </li>
                {%else%}

                    <li class="navbar-item {%if request.path == login%}active{%endif%}">
                        <a href ="{{login}}" class="nav-link">
                        <span class="fas fa-user"></span>    
                            Login</a>
                    </li>
                    <li class="navbar-item {%if request.path == register%}active{%endif%}">
                            <a href ="{{register}}" class="nav-link">
                            <span class="fas fa-user-plus"></span>   
                            Registro</a>
                    </li>
                {%endif%}

        </ul>
    </div>
</nav>

  

users/templates/users/register.html
{% extends "users/base.html" %}
{%load static%}
{% block content %}

  
        
       <div class="col">   
          <!--formulario-->
          <form method="POST">
          <h2>Registro</h2>
            {% csrf_token %}
            <div class="form_group">
              {%for field in form%} {{field.label_tag}} {{field}} 
              {%if field.errors%} {{field.errors}} {%endif%}
            </div>
            {%endfor%}

            <button type="submit" class="btn btn-primary">Registro</button>
          </form>
      </div>     
 
{%endblock content%}

users/templates/users/users_index.html
{% extends "users/base.html" %}
{%load static%}
{% block content %}
    <title>ecommerce Xalapa</title>
    <div class="col">
          {%include "products/snippets/search.html" %}
        {%include "products/snippets/list.html" %}
    </div>
    

{%endblock content%}